# ruff.toml
line-length = 100
target-version = "py311"

[lint]
select = [
    "F",    # Pyflakes (undefined names, unused imports)
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "I",    # isort (import sorting)
    "N",    # pep8-naming
    "UP",   # pyupgrade
    "TRY",  # tryceratops (unhandled exceptions, bad excepts)
]

ignore = [
    "E501",  # ignore line length errors (optional)
]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
